### PR TITLE
Fix Detox build on android

### PR DESCRIPTION
**Pull request by Andarius**
Fixes detox issue when building the app on android: wix/Detox#2712

### CODE REVIEW

**Comment by alpha0010** [comment]
Thank you.

**Comment by Andarius** [comment]
Thank you for your work!

**Comment by Andarius** [comment]
@alpha0010 , is it possible to release a new version? So that I add back this lib rather than a custom branch?

**Comment by alpha0010** [comment]
Was waiting on the iOS counterpart of #16, but it is not blocking.  Released.

**Pull request merged**
